services:
  renting-microservice:
    build:
      context: .
      dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
    image: renting-microservice:latest
    container_name: renting-microservice
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__RentingDatabase: Data Source=/data/renting.db
    volumes:
      - ./data:/data

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: renting-sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    command: sqlite_web /data/renting.db --host 0.0.0.0
    depends_on:
      - renting-microservice